import jsPDF from "jspdf";
import type { Scan, Finding } from "@/lib/api";

export function exportReportAsPdf(scan: Scan, findings: Finding[]) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const addPage = () => {
    doc.addPage();
    y = margin;
    // Footer on previous page
    addFooter(doc.getNumberOfPages() - 1);
  };

  const addFooter = (pageNum: number) => {
    doc.setPage(pageNum);
    doc.setFontSize(7);
    doc.setTextColor(140);
    doc.text(`ThreatLens — Confidential | Page ${pageNum} of [TOTAL]`, margin, pageHeight - 8);
    doc.text(`Report ID: TL-${scan.id.substring(0, 8).toUpperCase()}`, pageWidth - margin, pageHeight - 8, { align: "right" });
  };

  const checkPageBreak = (needed: number) => {
    if (y + needed > pageHeight - 20) {
      addPage();
    }
  };

  // === COVER PAGE ===
  doc.setFillColor(15, 17, 23);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  // Title
  doc.setTextColor(255);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("THREAT INTELLIGENCE", margin, 60);
  doc.text("ASSESSMENT REPORT", margin, 72);

  // Accent line
  doc.setDrawColor(120, 80, 220);
  doc.setLineWidth(1);
  doc.line(margin, 78, margin + 60, 78);

  // Domain
  doc.setFontSize(16);
  doc.setTextColor(120, 80, 220);
  doc.text(scan.domain, margin, 92);

  // Meta info
  doc.setFontSize(10);
  doc.setTextColor(180);
  doc.setFont("helvetica", "normal");
  const scanDate = new Date(scan.created_at).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric"
  });
  doc.text(`Report ID: TL-${scan.id.substring(0, 8).toUpperCase()}`, margin, 108);
  doc.text(`Date: ${scanDate}`, margin, 115);
  doc.text(`Risk Score: ${scan.risk_score}/100`, margin, 122);
  doc.text(`Total Findings: ${findings.length}`, margin, 129);
  doc.text(`URLs Discovered: ${scan.urls_found}`, margin, 136);

  // Classification
  doc.setFontSize(9);
  doc.setTextColor(220, 80, 80);
  doc.setFont("helvetica", "bold");
  doc.text("CLASSIFICATION: CONFIDENTIAL", margin, 160);
  doc.setTextColor(140);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("For authorized personnel only. Do not distribute without approval.", margin, 167);

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(100);
  doc.text("Generated by ThreatLens Automated Threat Intelligence Platform", margin, pageHeight - 15);

  // === FINDINGS SUMMARY PAGE ===
  addPage();
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  doc.setTextColor(30);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Findings Summary", margin, y);
  y += 12;

  // Severity table
  const sevCounts: Record<string, number> = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
  findings.forEach(f => {
    const s = f.severity.toLowerCase();
    if (sevCounts[s] !== undefined) sevCounts[s]++;
  });

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(80);
  doc.text("Severity", margin, y);
  doc.text("Count", margin + 50, y);
  doc.text("Weight", margin + 80, y);
  doc.text("Points", margin + 110, y);
  y += 2;
  doc.setDrawColor(200);
  doc.line(margin, y, margin + 130, y);
  y += 6;

  const weights: Record<string, number> = { critical: 25, high: 15, medium: 8, low: 3, info: 1 };
  const sevColors: Record<string, [number, number, number]> = {
    critical: [220, 60, 60], high: [240, 140, 40], medium: [220, 180, 40],
    low: [60, 180, 180], info: [120, 120, 140]
  };

  doc.setFont("helvetica", "normal");
  for (const [sev, count] of Object.entries(sevCounts)) {
    const [r, g, b] = sevColors[sev] || [80, 80, 80];
    doc.setTextColor(r, g, b);
    doc.setFont("helvetica", "bold");
    doc.text(sev.charAt(0).toUpperCase() + sev.slice(1), margin, y);
    doc.setTextColor(60);
    doc.setFont("helvetica", "normal");
    doc.text(String(count), margin + 50, y);
    doc.text(`×${weights[sev]}`, margin + 80, y);
    doc.text(String(count * (weights[sev] || 0)), margin + 110, y);
    y += 7;
  }

  y += 4;
  doc.setDrawColor(200);
  doc.line(margin, y, margin + 130, y);
  y += 6;
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30);
  doc.text(`Total Risk Score: ${scan.risk_score}/100`, margin, y);
  y += 14;

  // Findings list
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Detailed Findings", margin, y);
  y += 10;

  for (const f of findings) {
    checkPageBreak(30);
    const [r, g, b] = sevColors[f.severity.toLowerCase()] || [80, 80, 80];

    // Severity badge
    doc.setFillColor(r, g, b);
    doc.roundedRect(margin, y - 3.5, 18, 5.5, 1, 1, "F");
    doc.setFontSize(7);
    doc.setTextColor(255);
    doc.setFont("helvetica", "bold");
    doc.text(f.severity.toUpperCase(), margin + 1.5, y);

    // Category
    doc.setTextColor(120);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.text(f.category, margin + 22, y);

    y += 6;

    // Title
    doc.setTextColor(30);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(f.title, margin, y);
    y += 5;

    // Description
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(80);
    const descLines = doc.splitTextToSize(f.description || "", contentWidth);
    checkPageBreak(descLines.length * 4 + 4);
    doc.text(descLines, margin, y);
    y += descLines.length * 4 + 6;

    // Separator
    doc.setDrawColor(230);
    doc.line(margin, y, pageWidth - margin, y);
    y += 6;
  }

  // === AI REPORT PAGES ===
  if (scan.ai_report) {
    addPage();

    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30);
    doc.text("AI Threat Intelligence Report", margin, y);
    y += 12;

    const lines = scan.ai_report.split("\n");
    for (const line of lines) {
      if (line.startsWith("## ")) {
        checkPageBreak(14);
        y += 4;
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(30);
        doc.text(line.replace("## ", "").replace(/^\d+\.\s*/, ""), margin, y);
        y += 8;
      } else if (line.startsWith("### ")) {
        checkPageBreak(12);
        y += 2;
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(60);
        doc.text(line.replace("### ", "").replace(/^\d+\.\d+\s*/, ""), margin, y);
        y += 7;
      } else if (line.startsWith("- ") || line.startsWith("* ")) {
        checkPageBreak(6);
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(60);
        const bulletText = "• " + line.replace(/^[-*]\s*/, "").replace(/\*\*/g, "");
        const wrapped = doc.splitTextToSize(bulletText, contentWidth - 4);
        checkPageBreak(wrapped.length * 4);
        doc.text(wrapped, margin + 4, y);
        y += wrapped.length * 4 + 1;
      } else if (line.startsWith("**")) {
        checkPageBreak(6);
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(40);
        const boldText = line.replace(/\*\*/g, "");
        const wrapped = doc.splitTextToSize(boldText, contentWidth);
        doc.text(wrapped, margin, y);
        y += wrapped.length * 4 + 2;
      } else if (line.trim() === "") {
        y += 3;
      } else if (line.startsWith("---")) {
        checkPageBreak(8);
        doc.setDrawColor(200);
        doc.line(margin, y, pageWidth - margin, y);
        y += 6;
      } else {
        checkPageBreak(6);
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(60);
        const cleanLine = line.replace(/\*\*/g, "");
        const wrapped = doc.splitTextToSize(cleanLine, contentWidth);
        checkPageBreak(wrapped.length * 4);
        doc.text(wrapped, margin, y);
        y += wrapped.length * 4 + 1;
      }
    }
  }

  // Add footers with correct total page count
  const totalPages = doc.getNumberOfPages();
  for (let i = 2; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(140);
    doc.text(`ThreatLens — Confidential | Page ${i - 1} of ${totalPages - 1}`, margin, pageHeight - 8);
    doc.text(`Report ID: TL-${scan.id.substring(0, 8).toUpperCase()}`, pageWidth - margin, pageHeight - 8, { align: "right" });
  }

  const fileName = `ThreatLens_Report_${scan.domain.replace(/[^a-zA-Z0-9]/g, "_")}_${new Date(scan.created_at).toISOString().split("T")[0]}.pdf`;
  doc.save(fileName);
}
